### ISSUE TITLE
Define variable types, declare strict types, WordPress coding standard

### ISSUE THREAD

**Issue by gudmdharalds** [Automattic/vip-go-ci#157]
The code needs a bit of clean up in a few areas. This issue collects these and links to the appropriate issues/pull requests which resolve these issues.

The clean up involves:
* Currently only part of the code uses strict variable types. All the code should use strict variable types, as it is safer. 
* `declare(strict_types=1);` should be used in all files.
* All files should comply with the WordPress coding standard.

The above needs to be applied to the following files:
- [x] ap-file-types.php [ #247 ]
- [x] ap-hashes-api.php [ #247 ]
- [x] ap-nonfunctional-changes.php [ #247 ]
- [x] ap-svg-files.php [ #247 ]
- [x] auto-approval.php  [ #247 ]
- [x] defines.php  [ #247 ]
- [X] exec.php [ #236 ]
- [x] file-validation.php [ #272 ]
- [x] github-api.php  [ #272 ]
- [x] github-commit-status.php [ #247 ]
- [x] git-repo.php [ #272 ]
- [X] latest-release.php [ #247 ]
- [X] lint-scan.php [ #236 ]
- [X] main.php [ #207 ]
- [x] misc.php [ #272 ]
- [x] options.php [ #272 ]
- [x] other-web-services.php [ #272 ]
- [X] phpcs-scan.php [ #236 ]
- [X] requires.php [ #246 ]
- [x] results.php [ #247 ]
- [x] skip-file.php  [ #247 ]
- [x] statistics.php  [ #247 ]
- [x] support-level-label.php  [ #247 ]
- [X] svg-scan.php [ #236 ]
- [X] test.bootstrap.php  [ #247 ]
- [X] vip-go-ci.php [ #236 ]

Unit tests are covered in #244.
